name: 'Semantic Versioning Action'
description: 'Custom GitHub Action to increment version based on commit messages'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
outputs:
  version:
    description: 'The new semantic version'
runs:
  using: 'node20'
  main: 'index.js'