name: Versioning Workflow

on:
  push:
    branches: [main]

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Update to match the version you need

      - name: Install dependencies
        run: npm install

      - name: Run custom versioning action
        uses: ./actions/versioning-action
        id: version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print new version
        run: echo "New version is ${{ steps.version.outputs.version }}"
